[build]
  publish = "."
  
[[redirects]]
  from = "/*"
  to = "/index.htm"
  status = 200

[functions]
  directory = "netlify/functions"

# Scheduled functions for death checking
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

# Configure the scheduled function
[functions."check-deaths"]
  schedule = "@every 6h"  # Every 6 hours

[dev]
  command = "echo 'Static site - no dev server needed'"
  port = 8888
