[build]
  publish = "."
  
[[redirects]]
  from = "/*"
  to = "/index.htm"
  status = 200

[functions]
  directory = "netlify/functions"

# Death checking is handled by GitHub Actions
# See .github/workflows/death-check.yml

[dev]
  command = "echo 'Static site - no dev server needed'"
  port = 8888
