[build]
  publish = "."
  
[[redirects]]
  from = "/*"
  to = "/index.htm"
  status = 200

[functions]
  directory = "netlify/functions"

# Scheduled functions for death checking
# Run every 2 hours:
[functions."check-deaths"]
  schedule = "0 */2 * * *"

[dev]
  command = "echo 'Static site - no dev server needed'"
  port = 8888
