[build]
  publish = "."
  
[[redirects]]
  from = "/*"
  to = "/index.htm"
  status = 200

[functions]
  directory = "netlify/functions"

# Scheduled functions for death checking
# Run every 4 hours: 00:00, 04:00, 08:00, 12:00, 16:00, 20:00 UTC
[functions."check-deaths"]
  schedule = "0 */2 * * *"

[dev]
  command = "echo 'Static site - no dev server needed'"
  port = 8888
